### ISSUE TITLE
rsyncd state broken

### ISSUE THREAD

**Issue by jpic** [martinhoefling/rsyncd-formula#2]
While `rsyncd.config` works, `rsyncd` by itself fails: https://travis-ci.org/martinhoefling/rsyncd-formula/builds/62625994

I'm going to focus on improving the test suite, ie. add idempotence checks. It would be great if you could fix it.

Thanks for sharing your formula, it's awesome !!!

**Comment by martinhoefling** [comment]
Merged from travis-refactoring branch.
